baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jensen's Blog"
theme = "cocoa-eh"
copyright = "Jensen"

[Author]
    name = "Jensen"

[Permalinks]
    posts = "/:year/:month/:day/:filename/"

[Taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
    intro = true
    headline = "Homepage"
    github = "JensenJiang"
    dateform = "2006-01-02"
    dateformfull = "Mon Jan 2 2006"
    latestpostcount = 5
    faviconfile = "/images/avatar.png"
    logofile = ""
    noreadingtime = false
    [params.mathjax]
        enable = true
        cdn = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"

[[menu.main]]
    name = "Homepage"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "Series"
    url = "/series"
    weight = 4
